name: Create pull request when main branch is updated
on:
  push:
    branches:
      - main

env:
  REPO_ID: my-cost-management-web

jobs:
  create-pr:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Verify build
        run: yarn build
      - name: Create PR
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/longlt201203/${{ env.REPO_ID }}/pulls \
          -d '{"title":"Deploy dev","body":"Deploy to dev server trigged by github ci","head":"${{ github.actor }}:main","base":"deploy/dev"}'
